### ISSUE TITLE
The PPI dataset link is invalid: https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/ppi.zip

### ISSUE THREAD

**Issue by HymEric** [CrawlScript/tf_geometric#13]
It seems the PPI dataset link is invalid: https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/ppi.zip

**Comment by hujunxianligong** [comment]
Thanks, I'll fix this as soon as possible.

**Comment by hujunxianligong** [comment]
The problem has been fixed in 0.0.31.
