### ISSUE TITLE
some questions about installation

### ISSUE THREAD

**Issue by tinmodeHuang** [CrawlScript/tf_geometric#25]
I don't expect that existing packages are updated  with the command ```pip install -U tf_geometric[tf2-gpu]```(e.g. existing release version 2.4.1 of Tensorflow isn't expected to upgrade), how shall I do?

**Comment by hujunxianligong** [comment]
Just use the command :
`pip install -U tf_geometric`

This command will not install or update tensorflow.

**Comment by tinmodeHuang** [comment]
sorry for being careless, just pay attention to it
