### ISSUE TITLE
请问怎么支持mini batch方式训练呢

### ISSUE THREAD

**Issue by Changzhisong** [CrawlScript/tf_geometric#29]
请问怎么支持mini batch方式训练呢？

**Comment by hujunxianligong** [comment]
假如你有一个graph list: graphs，那么构建一个batch_graph即可
batch_graph = tfg.BatchGraph.from_graphs(graphs)
因为tfg.BatchGraph继承自tfg.Graph，所以你可以对它使用任何GNN层。
由于batch_graph.y也是多个graphs组合的结果，你可以直接用它来计算损失。

仓库里提供的Graph Pooling的Demo，基本都用到了这个，比如：
https://github.com/CrawlScript/tf_geometric/blob/master/demo/demo_mean_pool.py

可以加QQ群讨论：535148548
